# Generated by Django 2.2.2 on 2019-06-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190625_1644'),
        ('article', '0003_auto_20190625_1646'),
    ]

    operations = [
    ]
