# Generated by Django 2.2.2 on 2019-07-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_merge_20190627_1334'),
        ('account', '0001_initial'),
        ('comment', '0003_auto_20190702_0552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ArticleComment',
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'Article Comment', 'verbose_name_plural': 'Article Comments'},
        ),
    ]
