# Generated by Django 2.2.2 on 2019-07-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20190705_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='article_id',
            new_name='article',
        ),
    ]
