# Generated by Django 2.2.2 on 2019-07-11 16:20

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20190705_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='author',
            field=models.CharField(help_text='Please enter valid email', max_length=500),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Please enter the Body of Comment', null=True),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='timespan_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
