# Generated by Django 2.2.2 on 2019-07-15 06:40

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20190711_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Please enter valid email', max_length=500)),
                ('timespan_created', models.DateTimeField(default=datetime.datetime.now)),
                ('timespan_updated', models.DateTimeField(auto_now=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Please enter the Answer to the Comment', null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.ArticleComment')),
            ],
            options={
                'verbose_name': 'Article Comment',
                'verbose_name_plural': 'Article Comments',
            },
        ),
    ]
